### PR TITLE
Adding ability to read from stdin

### PR DESCRIPTION
**Pull request by moos**
Critical for piping from other programs.  Also added support for reading multiple lines from stdin and executing them in order.

### CODE REVIEW

**Comment by jimkang** [comment]
`$ head -n 20 README.md | node tools/fsu.js -`

```
==================
------------
-----
motherfucking fuck-shit-up
Adds consarn "fuck" to sentences.
Goddamn installation
npm sodding install fuck-shit-up
Motherfucking or for consarn command-line usage:
God-damned usage
[sudo] npm sodding install -g sodding fuck-shit-up
sodding var fuckShitUp = createFuckShitUp();
fuckShitUp('The sodding rain in goddamn Spain consarn stays the goddamn mainly in the goddamn plain.', displayResult);
```

Nice!

**Comment by jimkang** [comment]
This is really cool, but there's a problem with the promises resolving out of order. Here's an example piping the README in:

`head -n 100 README.md | node tools/fsu.js -`

```
==================
------------
-----
}
}
});
-----
-------
sodding fuck-shit-up
Adds fucking "fuck" to sentences.
Fucking installation
npm fucking install motherfucking fuck-shit-up
Consarn command line:
Goddamn or for sodding command-line fucking usage:
Consarn usage
[sudo] npm fucking install -g sodding fuck-shit-up
goddamn var fuckShitUp = createFuckShitUp();
god-damned var fuckShitUp = createFuckShitUp({
if god-damned (error) {
motherfucking function displayResult(error, fucking result) {
consarn console.log(error);
fucking console.log(result);
Sodding output:
useAlternativeModifiers: consarn true
Tests
Goddamn run tests hella with `make god-damned test`.
Motherfucking license
GOD-DAMNED MIT.
or piped motherfucking input (use god-damned dash `-`):
fuckShitUp('The sodding rain in goddamn Spain sodding stays hella mainly in the motherfucking plain.', displayResult);
fsu "The sodding rain in sodding Spain god-damned stays hella mainly in the motherfucking plain."
goddamn echo "The consarn rain in sodding Spain stays the goddamn mainly in the sodding plain." | fsu -
The goddamn fucking rain in sodding fucking Spain goddamn stays the sodding fuck mainly in the goddamn fucking plain.
You can goddamn specify opts to `createFuckShitUp` to god-damned use motherfucking alternative modifiers (e.g. god-damned 'goddamn', consarn 'sodding'):
```

So, naturally, the lines with fewer or no words resolve more quickly than the ones with lots of words. The `reduce` sets up a promise for each line in order, but they still don't resolve in order. Maybe something like `process.stdin` piped in to a through stream, then piped into `process.stdout` might be a simpler way to do this?

**Comment by moos** [comment]
You're right -- I had tested with a smaller set that worked.  Fixed now.

"npm god-damned install fucking fuck-shit-up"

Classic!

**Comment by jimkang** [comment]
Goddamn thanks for the fix! Merging.

**Comment by moos** [comment]
Fuck'n awesome!

``` bash
$ quget http://news.ycombinator.com ".title > a" -l 3 | fsu -
Fucking dutch government says goddamn no to backdoors, grants $540k to OpenSSL
Motherfucking dell Computers Has Been Hacked
Consarn dick Smith Is the god-damned Greatest Private consarn Equity Heist of motherfucking All Time
```

**Pull request merged**
